import { HashMap, HashSet } from "./hashing.js"

const test = new HashMap()
test.set('apple', 'red')
test.set('banana', 'yellow')
test.set('carrot', 'orange')
test.set('dog', 'brown')
test.set('elephant', 'gray')
test.set('frog', 'green')
test.set('grape', 'purple')
test.set('hat', 'black')
test.set('ice cream', 'white')
test.set('jacket', 'blue')
test.set('kite', 'pink')
test.set('lion', 'golden')
console.log(`Hash Map before capacity change:`)
console.log(test.entries())

test.set('moon', 'silver')
console.log(`Hash Map after capacity change:`)
console.log(test.entries())
test.set('coco', 'white-brown-gray')
test.set('Ali', 'tan')
test.set('MacNCheese', 'mac-and-cheese')
test.set('Charlie', 'Kirk')
test.set('Wman', 'bluegreen')
console.log(`Hash Map after new custom values:`)
console.log(test.entries())
console.log(`Getting Ali's value if he exists in Hash Map: ${test.get("Ali")}`)
console.log(`Finding out if there is Ali on the Hash Map: ${test.has("Ali")}`)
console.log(`Getting all Keys of Hash Map:`)
console.log(test.keys())
console.log(`Getting all Values of Hash Map:`)
console.log(test.values())
console.log(`Length of Hash Map: ${test.length()}`)
console.log(`Getting DNE's value if he exists in Hash Map: ${test.get("DNE")}`)
console.log(`Finding out if there is DNE on the Hash Map: ${test.has("DNE")}`)
console.log(`Clearing:`)
test.clear()
console.log(`Hash Map after Clearing:`)
console.log(test.entries())
for (let i = 0; i < 10; i++) {
    console.log("")
}
const testSet = new HashSet()
testSet.set('apple')
testSet.set('banana')
testSet.set('carrot')
testSet.set('dog')
testSet.set('elephant')
testSet.set('frog')
testSet.set('grape')
testSet.set('hat')
testSet.set('ice cream')
testSet.set('jacket')
testSet.set('kite')
testSet.set('lion')
console.log(`Hash Set before capacity change:`)
console.log(testSet.entries())
testSet.set('moon')
console.log(`Hash Set after capacity change:`)
console.log(testSet.entries())
testSet.set('coco')
testSet.set('Ali')
testSet.set('MacNCheese')
testSet.set('Charlie')
testSet.set('Wman')
console.log(`Hash Set after new custom values:`)
console.log(testSet.entries())
console.log(`Getting Ali's key if he exists in Hash Set: ${testSet.get("Ali")}`)
console.log(`Finding out if there is a key Ali on the Hash Set: ${testSet.has("Ali")}`)
console.log(`Length of Hash Set: ${testSet.length()}`)
console.log(`Getting DNE's value if he exists in Hash Map: ${testSet.get("DNE")}`)
console.log(`Finding out if there is DNE on the Hash Map: ${testSet.has("DNE")}`)
console.log(`Clearing:`)
testSet.clear()
console.log(`Hash Set after Clearing:`)
console.log(testSet.entries())

